### ISSUE TITLE
Latest release broke our build script...

### ISSUE THREAD

**Issue by ponychicken** [hallee/eslint-action#7]
After the changes today our workflow returns:

````
2020-05-19T15:51:27.1379668Z Error Error: Received status code 401
2020-05-19T15:51:27.1379834Z     at IncomingMessage.res.on (/action/lib/request.js:13:25)
2020-05-19T15:51:27.1379941Z     at IncomingMessage.emit (events.js:203:15)
2020-05-19T15:51:27.1380059Z     at endReadableNT (_stream_readable.js:1145:12)
2020-05-19T15:51:27.1380174Z     at process._tickCallback (internal/process/next_tick.js:63:19)
2020-05-19T15:51:27.1380385Z {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
````

(running here: https://github.com/ponychicken/WebsterParser/runs/687909011?check_suite_focus=true )

**Comment by darshkpatel** [comment]
Similar github Actions API related bug can be seen here 
https://github.com/hallee/eslint-action/pull/11/checks?check_run_id=692215926

```
{"message":"Resource not accessible by integration","documentation_url":"https://developer.github.com/v3/checks/runs/#create-a-check-run"}
```

**Comment by hallee** [comment]
@ponychicken This was because you set `GITHUB_TOKEN` via an env variable, which a recent change broke. Sorry about that.

Should be fixed now if you re-run your action.
